### PR TITLE
Team-3 Basic/ Basic Middleware/ Test Passing

### PR DESCRIPTION
**Pull request by JacobGregor**

### CODE REVIEW

**Review by JacobKnaack — CHANGES_REQUESTED** [review]
This looks great, make sure you pull from the upstream origin and if your tests are passing than your merge is approved!

**Review by JacobGregor — COMMENTED** [review]
Looks good to me as well

**Comment by JacobGregor** [comment]
Are you asking to pull upstream once these changes are submitted or prior? Im having an issue pulling upstream when I try the command.

**Comment by JacobKnaack** [comment]
> 

I just made updates to the repo since you created the PR.  It's a good idea to merge locally and to get the github action so that CI runs on your fork.

**Review by JacobKnaack — APPROVED** [review]

**Pull request merged**
